### ISSUE TITLE
restore mode

### ISSUE THREAD

**Issue by gio82c** [zacs/ha-dualmodegeneric#1]
Hi Zacs,

there is a way to restore the state from cool to cool when i send cmd climate.turn_off and turn on again?

now if is in cool mode and turn off the thermostat when i turn on star on heat mode.

**Comment by zacs** [comment]
Hmm, that isn't the intended behavior and I've not seen it happen that way. Can you enable logging and paste what you get? To enable logging add this to your conf

```
logger:
  default: info
  logs:
    custom_components.dualmode_generic: debug
```
