### ISSUE TITLE
Help with combined compressor + fan mode

### ISSUE THREAD

**Issue by mjsambol** [zacs/ha-dualmodegeneric#27]
Hi, thanks for your work on this component, it's much appreciated!

I have a central A/C system and am trying to reproduce two separate cooling modes which are offered by some thermostats: one in which the fan runs full-time, with the compressor turning on and off periodically, and the other in which the fan only runs when the compressor is on.

I have a series of relay switches connected to the fan, compressor, and heat pump.

I wanted to use "cool" for the constant fan + occasional compressor mode, and "dry" for the synchronized fan+compressor. I got dry running by using a template switch which turns the fan and compressor on together. For "cool", I made an automation that simply monitors the state of the climate component and turns on the fan when it enters "cool" state. 

**"Dry" works fine, but in "cool" mode, after the first time the compressor turns off, it never turns on again.**

My configuration:

```
climate:
  - platform: dualmode_generic
    name: Upstairs Thermostat
    heater: switch.upstairs_thermostat_heat_with_fan
    cooler: switch.upstairs_thermostat_compressor
    fan: switch.upstairs_thermostat_fan
    fan_behavior: neutral
    dryer: switch.upstairs_thermostat_cool_with_fan
    dryer_behavior: cooler
    target_sensor: sensor.master_bedoom_temp
    enable_heat_cool: False
    min_temp: 16
    max_temp: 30
    cold_tolerance: 0.5
    hot_tolerance: 0.5
    min_cycle_duration:
        minutes: 8
```

switch.upstairs_thermostat_fan and switch.upstairs_thermostat_compressor are relays which close the physical circuits powering the system. These work fine.

```
switch:
  - platform: template
    switches:
      upstairs_thermostat_cool_with_fan:
        value_template: "{{ states.variable.upstairs_thermostat_cool_with_fan.state }}"
        turn_on:
          - service: homeassistant.turn_on
            target:
              entity_id: switch.upstairs_thermostat_fan
          - service: homeassistant.turn_on
            target:
              entity_id: switch.upstairs_thermostat_compressor
          - service: variable.set_variable
            data_template:
              variable: upstairs_thermostat_cool_with_fan
              value: true
        turn_off:
          - service: homeassistant.turn_off
            target:
              entity_id: switch.upstairs_thermostat_compressor
          - service: homeassistant.turn_off
            target:
              entity_id: switch.upstairs_thermostat_fan
          - service: variable.set_variable
            data_template:
              variable: upstairs_thermostat_cool_with_fan
              value: false
```

Can you help me understand why the compressor is misbehaving in "cool" mode?

Looking in the log file, when I am using the "dryer" mode (which works fine), I see the expected log lines
`Turning on dehumidifier switch.upstairs_thermostat_cool_with_fan` 
and similar for turning off. But when in "cool" mode there are no log lines.
