### ISSUE TITLE
[Bug] Thermostat not displaying range

### ISSUE THREAD

**Issue by peanutsguy** [zacs/ha-dualmodegeneric#35]
After updating to 72664fe the thermostat stopped displaying the range for `heat_cool`

```
climate:
  - platform: dualmode_generic
    name: "Bedroom Thermostat"
    unique_id: bedroom_thermostat
    heater: switch.bedroom_heater
    cooler: switch.bedroom_fan
    target_sensor: sensor.bedroom_temperature
    cold_tolerance: 0.3
    hot_tolerance: 0.3
    min_temp: 16
    max_temp: 30
    min_cycle_duration:
      minutes: 1
    precision: 0.1
    enable_heat_cool: True
```
Home Assistant
Platform: | Docker
-- | --
Version: | core-2021.8.7

HACS
Integration version: | 1.13.2
-- | --
Frontend version: | 20210620205902

Dual-Mode Generic Thermostat
Version: 72664fe

![dualmode_generic](https://user-images.githubusercontent.com/5214572/129826133-966baca0-4e31-4144-94da-1e6d8c423646.png)
![dualmode_generic2](https://user-images.githubusercontent.com/5214572/129826136-d77b86de-57e5-411f-9391-0bc5639ad9d2.png)
