### ISSUE TITLE
Thermostat won't stop heating

### ISSUE THREAD

**Issue by BebeMischa** [zacs/ha-dualmodegeneric#47]
Hello,

just installed today and trying to get it to work, but it won't stop heating when temperature is reached.

HA supervised 2022.2.0, HACS 1.21.0, Dual thermostat cb0d234

code:
```
# Thermostaten
climate:
  - platform: dualmode_generic
    name: Rotkast
    unique_id: climate.rotkast
    heater: switch.sonoff_1001041627
    cooler: switch.sonoff_100103c57c
    target_sensor: sensor.aeotec_humitemp_rotkast_air_temperature
    enable_heat_cool: True
    min_temp: 8
    max_temp: 42
    cold_tolerance: 0.1
    hot_tolerance: 0.1
    min_cycle_duration:
      minutes: 2
```

And here I'm looking at now:

![image](https://user-images.githubusercontent.com/73079275/152432942-fc1e43b9-0c87-4cbd-8c4b-230af6edb238.png)

Temperature is set to 29,9 - 30.1 , tolerances are both 0.1 but it still won't stop heating.

I have waited for it to stop foe 30 minutes. Then I set the thermostat to off and on again and it immediately started cooling. And yes, it kept cooling way below the set temperature. Until I shut it off and on. It started heating. Very strange...

Something wrong on my side?

Thanks in advance for you help ;-)
