### ISSUE TITLE
How can I get the reverse_cycle to work?

### ISSUE THREAD

**Issue by Legendhidde** [zacs/ha-dualmodegeneric#52]
Hi, I've been trying to get this thermostat to work for a while now with my Mitsubishi aircon. I can cool, heat, dry and fan with it but I was wondering what I need to set as cooler, heater, dryer and fan in the configuration.yaml.

Simply adding the airconditioning entity ID doesn't seem like it would work as my aircon works with a command like:           

```
- service: climate.set_hvac_mode
            data:
              hvac_mode: heat
            target:
              device_id: 0d36b2068f1d3e9092012e2e
```

Although I don't think this works properly. What I did to try to solve this was create a couple of switch templates that would call the service and turn the airconditioner to heat and a preset temperature. Although this doesn't seem like the best solution either as I'm sure smart people have already gotten this to work without those switching templates. It would also be preferable to set the temperature of the airconditioner based on the temperature set in the thermostat. So that when the aircon turns on while the thermostat is set to 18 then the temperature set on the airco should also be 18.

```
      aircocool:
        value_template: "{{ is_state('climate.airco_living_room', 'cool') }}"
        turn_on:
          - service: climate.set_temperature
            data:
             hvac_mode: cool
             temperature: 25
            target:
             device_id: 0d36b2068f1d3e9092012e2ed73cd0ff
        turn_off:
          - service: climate.turn_off
            data: {}
            target:
             device_id: 0d36b2068f1d3e9092012e2ed73cd0ff
```
