### ISSUE TITLE
Log warns about target temperature range while target range disabled.

### ISSUE THREAD

**Issue by miguelangel-nubla** [zacs/ha-dualmodegeneric#68]
I am seeing warnings on the logs:
```
2024-05-04 13:24:53.352 WARNING (MainThread) [custom_components.dualmode_generic.climate] Undefined target temperature range,falling back to 20.0 to 26.0
```
with this configuration:
```
  - platform: dualmode_generic
    name: thermostat_bathroom1
    unique_id: thermostat_bathroom1
    heater: switch.floor1_underfloor_controller_loop3
    cooler: switch.floor1_underfloor_controller_loop3
    target_sensor: sensor.bathroom1_thermostat_temperature
    target_temp_step: 0.5
    reverse_cycle: cooler, heater
    min_temp: 20
    max_temp: 26
    cold_tolerance: 0
    hot_tolerance: 0
    min_cycle_duration:
      minutes: 0
```

Shouldn't `enable_heat_cool` be `false` by default?
Therefore, should the warning not be issued because there is no target range?
